version: '3.8'

services:
  quantum-ai-head:
    build: .
    ports:
      - "8000:8000"
      - "10001:10001"  # Ray head node
    environment:
      - RAY_HEAD_NODE=true
      - QUANTUM_BACKEND=qasm_simulator
      - SECURITY_LEVEL=5
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      - redis
      - postgres
    networks:
      - quantum-net

  quantum-ai-worker:
    build: .
    environment:
      - RAY_HEAD_NODE=false
      - RAY_HEAD_HOST=quantum-ai-head
      - QUANTUM_BACKEND=qasm_simulator
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      - quantum-ai-head
    networks:
      - quantum-net
    deploy:
      replicas: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - quantum-net

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-quantum_agi}
      - POSTGRES_USER=${POSTGRES_USER:-agi_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - quantum-net

  monitoring:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - quantum-net

volumes:
  redis-data:
  postgres-data:
  prometheus-data:

networks:
  quantum-net:
    driver: bridge
