version: '3.8'

services:
  # Priority 1: Dream Recall API
  dream-recall:
    build: 
      context: .
      dockerfile: tools/scripts/docker/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - API_NAME=Dream Recall API
      - PORT=8001
      - LUKHAS_ENV=demo
    command: python apis/create_dream_recall_api.py
    restart: unless-stopped

  # Priority 2: Memory Fold API  
  memory-fold:
    build:
      context: .
      dockerfile: tools/scripts/docker/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - API_NAME=Memory Fold API
      - PORT=8003
      - LUKHAS_ENV=demo
    command: python apis/create_memory_fold_api.py
    restart: unless-stopped

  # Priority 3: QRG Authentication (placeholder for now)
  # qrg-auth:
  #   build:
  #     context: .
  #     dockerfile: tools/scripts/docker/Dockerfile
  #   ports:
  #     - "8007:8007"
  #   environment:
  #     - API_NAME=QRG Authentication API
  #     - PORT=8007
  #   command: python apis/create_qrg_auth_api.py

  # Priority 4: Emotional Coherence API
  emotional-coherence:
    build:
      context: .
      dockerfile: tools/scripts/docker/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - API_NAME=Emotional Coherence API
      - PORT=8002
      - LUKHAS_ENV=demo
    command: python apis/create_emotional_coherence_api.py
    restart: unless-stopped

  # Priority 5: Colony Consensus API
  colony-consensus:
    build:
      context: .
      dockerfile: tools/scripts/docker/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - API_NAME=Colony Consensus API
      - PORT=8004
      - LUKHAS_ENV=demo
    command: python apis/create_colony_consensus_api.py
    restart: unless-stopped

  # Classical Alternatives (for safety)
  classical-dream:
    build:
      context: .
      dockerfile: tools/scripts/docker/Dockerfile
    ports:
      - "8005:8005"
    environment:
      - API_NAME=Classical Dream API
      - PORT=8005
      - LUKHAS_ENV=demo
    command: python apis/create_classical_dream_api.py
    restart: unless-stopped

  classical-emotional:
    build:
      context: .
      dockerfile: tools/scripts/docker/Dockerfile
    ports:
      - "8006:8006"
    environment:
      - API_NAME=Classical Emotional API
      - PORT=8006
      - LUKHAS_ENV=demo
    command: python apis/create_classical_emotional_api.py
    restart: unless-stopped

  # Demo Dashboard (Nginx serving static files)
  dashboard:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./docs/presentation:/usr/share/nginx/html
      - ./tools/scripts/docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dream-recall
      - memory-fold
      - emotional-coherence
      - colony-consensus

networks:
  default:
    name: lukhas-demo-network