version: '3.8'

services:
  lukhas-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: lukhas/lukhas-agi:dev
    container_name: lukhas-dev
    ports:
      - "8000:8000"
    environment:
      - LUKHAS_ENV=development
      - LUKHAS_DEBUG=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORGANIZATION=${OPENAI_ORGANIZATION}
    volumes:
      - .:/app
      - /app/venv
      - /app/.git
      - /app/__pycache__
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - lukhas-dev-network
    command: ["uvicorn", "lukhas.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

networks:
  lukhas-dev-network:
    driver: bridge