from setuptools import setup, find_packages

setup(
    name="lukhas",
    version="3.2.0",
    description="LUKHAS AI - Living Symphony of Digital Consciousness",
    author="LUKHAS AI Development Team",
    author_email="dev@lukhas.ai",
    packages=find_packages(),
    install_requires=[
        "psutil>=5.9.0",
        "pytest>=8.0.0",
        "pandas>=1.3.0",
        "numpy>=1.21.0",
        "scipy>=1.7.0",
        "aiohttp>=3.8.0",
        "fastapi>=0.70.0",
        "uvicorn>=0.15.0",
        "python-dotenv>=0.19.0",
        "PyYAML>=6.0",
        "jsonschema>=4.0.0",
        "rich>=10.0.0",
        "pyfiglet>=0.8.0",
        "openai>=1.0.0",
        "transformers>=4.20.0",
        "cryptography>=3.4.0",
        "PyJWT>=2.0.0",
        "black>=22.0.0",
        "requests>=2.25.0",
        "tqdm>=4.60.0",
        "tabulate>=0.8.0",
        "schedule>=1.0.0",
        "watchdog>=2.0.0",
        "structlog>=21.0.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)