"""
Creativity System - Auto-generated entity exports
Generated from entity activation scan
Total entities: 572
"""

# Lazy imports to avoid circular dependencies
import importlib
import logging

logger = logging.getLogger(__name__)

# Entity registry for lazy loading
_ENTITY_REGISTRY = {
    "AdvancedHaikuGenerator": ("advanced_haiku_generator", "AdvancedHaikuGenerator"),
    "QuantumHaikuGenerator": ("advanced_haiku_generator", "QuantumHaikuGenerator"),
    "NeuroHaikuGenerator": ("advanced_haiku_generator", "NeuroHaikuGenerator"),
    "AffectStagnationDetector": ("affect_stagnation_detector", "AffectStagnationDetector"),
    "CreativeStyle": ("creative_engine", "CreativeStyle"),
    "ExpansionStrategy": ("creative_engine", "ExpansionStrategy"),
    "CreativeConfig": ("creative_engine", "CreativeConfig"),
    "CreativeMetrics": ("creative_engine", "CreativeMetrics"),
    "CreativeContext": ("creative_engine", "CreativeContext"),
    "NeuralCreativeModel": ("creative_engine", "NeuralCreativeModel"),
    "SymbolicKnowledgeBase": ("creative_engine", "SymbolicKnowledgeBase"),
    "FederatedLearningClient": ("creative_engine", "FederatedLearningClient"),
    "CircuitBreaker": ("creative_engine", "CircuitBreaker"),
    "AdvancedSyllableAnalyzer": ("creative_engine", "AdvancedSyllableAnalyzer"),
    "EnterpriseNeuralHaikuGenerator": ("creative_engine", "EnterpriseNeuralHaikuGenerator"),
    "CreativeEngineFactory": ("creative_engine", "CreativeEngineFactory"),
    "MockNeuralModel": ("creative_engine", "MockNeuralModel"),
    "MockSymbolicKB": ("creative_engine", "MockSymbolicKB"),
    "MockFederatedClient": ("creative_engine", "MockFederatedClient"),
    "NeuroHaikuGenerator": ("creative_expression_core", "NeuroHaikuGenerator"),
    "CreativeItem": ("creative_market", "CreativeItem"),
    "CreativeMarket": ("creative_market", "CreativeMarket"),
    "CreativeQuantumLikeState": ("creative_q_expression", "CreativeQuantumLikeState"),
    "CreativeExpressionProtocol": ("creative_q_expression", "CreativeExpressionProtocol"),
    "QuantumCreativeEngine": ("creative_q_expression", "QuantumCreativeEngine"),
    "QuantumHaikuGenerator": ("creative_q_expression", "QuantumHaikuGenerator"),
    "QuantumMusicComposer": ("creative_q_expression", "QuantumMusicComposer"),
    "BioCognitiveCreativityLayer": ("creative_q_expression", "BioCognitiveCreativityLayer"),
    "CreativeIPProtector": ("creative_q_expression", "CreativeIPProtector"),
    "CollaborativeCreativityOrchestrator": ("creative_q_expression", "CollaborativeCreativityOrchestrator"),
    "AdaptiveCreativePersonalization": ("creative_q_expression", "AdaptiveCreativePersonalization"),
    "LukhasCreativeExpressionEngine": ("creative_q_expression", "LukhasCreativeExpressionEngine"),
    "EnhancedNeuroHaikuGenerator": ("creative_q_expression", "EnhancedNeuroHaikuGenerator"),
    "DreamWeaver": ("dream.base.dream_refold.dream_refold", "DreamWeaver"),
    "DummyMemory": ("dream.base.dream_refold.dream_refold", "DummyMemory"),
    "DreamProcessor": ("dream.cli.dream_processor", "DreamProcessor"),
    "DreamTaskType": ("dream.colony_dream_coordinator", "DreamTaskType"),
    "DreamDistributionStrategy": ("dream.colony_dream_coordinator", "DreamDistributionStrategy"),
    "ColonyDreamTask": ("dream.colony_dream_coordinator", "ColonyDreamTask"),
    "ColonyDreamResult": ("dream.colony_dream_coordinator", "ColonyDreamResult"),
    "ColonyDreamCoordinator": ("dream.colony_dream_coordinator", "ColonyDreamCoordinator"),
    "ColonyOrchestrator": ("dream.colony_dream_coordinator", "ColonyOrchestrator"),
    "ColonyType": ("dream.colony_dream_coordinator", "ColonyType"),
    "ColonyPriority": ("dream.colony_dream_coordinator", "ColonyPriority"),
    "DreamPhase": ("dream.core", "DreamPhase"),
    "DreamType": ("dream.core", "DreamType"),
    "DreamState": ("dream.core", "DreamState"),
    "DreamContent": ("dream.core", "DreamContent"),
    "DreamCycle": ("dream.core", "DreamCycle"),
    "DreamModule": ("dream.core", "DreamModule"),
    "DreamMetricsDB": ("dream.dashboard.dream_metrics_db", "DreamMetricsDB"),
    "DreamMetrics": ("dream.dashboard.dream_metrics_view", "DreamMetrics"),
    "DreamMetricsView": ("dream.dashboard.dream_metrics_view", "DreamMetricsView"),
    "DreamDataCollector": ("dream.dream_data_sources", "DreamDataCollector"),
    "OracleDreamGenerator": ("dream.dream_engine.oracle_dream", "OracleDreamGenerator"),
    "EnhancedOracleDreamGenerator": ("dream.dream_engine.oracle_dream", "EnhancedOracleDreamGenerator"),
    "UnifiedDreamPipeline": ("dream.dream_pipeline", "UnifiedDreamPipeline"),
    "MockConsent": ("dream.dream_pipeline", "MockConsent"),
    "MockMemorySampler": ("dream.dream_pipeline", "MockMemorySampler"),
    "MediaInput": ("dream.dream_sandbox", "MediaInput"),
    "AIGeneratedDream": ("dream.dream_sandbox", "AIGeneratedDream"),
    "SimpleInterpretation": ("dream.dream_sandbox", "SimpleInterpretation"),
    "DreamInterpreter": ("dream.dream_sandbox", "DreamInterpreter"),
    "SimpleRLCycle": ("dream.dream_sandbox", "SimpleRLCycle"),
    "DreamSandbox": ("dream.dream_sandbox", "DreamSandbox"),
    "AdvancedDreamEngine": ("dream.engine.advanced_dream_engine", "AdvancedDreamEngine"),
    "MockBioOrchestrator": ("dream.engine.advanced_dream_engine", "MockBioOrchestrator"),
    "MockUnifiedIntegration": ("dream.engine.advanced_dream_engine", "MockUnifiedIntegration"),
    "DreamEngine": ("dream.engine.dream_engine", "DreamEngine"),
    "HelixMapper": ("dream.engine.dream_engine", "HelixMapper"),
    "CognitiveVoiceEngine": ("dream.engine.dream_engine", "CognitiveVoiceEngine"),
    "DreamPhase": ("dream.engine.dream_engine_merged", "DreamPhase"),
    "DreamState": ("dream.engine.dream_engine_merged", "DreamState"),
    "DreamEngine": ("dream.engine.dream_engine_merged", "DreamEngine"),
    "DreamEngineOptimizer": ("dream.engine.dream_engine_optimizer", "DreamEngineOptimizer"),
    "DreamFeedbackPropagator": ("dream.feedback_propagator", "DreamFeedbackPropagator"),
    "DreamSnapshotStore": ("dream.feedback_propagator", "DreamSnapshotStore"),
    "SimulationType": ("dream.hyperspace_dream_simulator", "SimulationType"),
    "TimelineState": ("dream.hyperspace_dream_simulator", "TimelineState"),
    "CausalConstraint": ("dream.hyperspace_dream_simulator", "CausalConstraint"),
    "HyperspaceVector": ("dream.hyperspace_dream_simulator", "HyperspaceVector"),
    "TimelineBranch": ("dream.hyperspace_dream_simulator", "TimelineBranch"),
    "SimulationScenario": ("dream.hyperspace_dream_simulator", "SimulationScenario"),
    "HyperspaceDreamSimulator": ("dream.hyperspace_dream_simulator", "HyperspaceDreamSimulator"),
    "DataType": ("dream.hyperspace_dream_simulator", "DataType"),
    "ModalityData": ("dream.hyperspace_dream_simulator", "ModalityData"),
    "QuantumLikeStateModifier": ("dream.modifiers.quantum_state_modifier", "QuantumLikeStateModifier"),
    "DreamSymbol": ("dream.oneiric_engine.demo.dream_interpreter", "DreamSymbol"),
    "DreamInterpretation": ("dream.oneiric_engine.demo.dream_interpreter", "DreamInterpretation"),
    "DreamEntry": ("dream.oneiric_engine.demo.dream_interpreter", "DreamEntry"),
    "LLMConfig": ("dream.oneiric_engine.demo.dream_interpreter", "LLMConfig"),
    "MediaInput": ("dream.oneiric_engine.demo.dream_interpreter", "MediaInput"),
    "VoiceInput": ("dream.oneiric_engine.demo.dream_interpreter", "VoiceInput"),
    "DreamEnrichment": ("dream.oneiric_engine.demo.dream_interpreter", "DreamEnrichment"),
    "AIGeneratedDream": ("dream.oneiric_engine.demo.dream_interpreter", "AIGeneratedDream"),
    "DreamInterpreter": ("dream.oneiric_engine.demo.dream_interpreter", "DreamInterpreter"),
    "MultimediaProcessor": ("dream.oneiric_engine.demo.dream_interpreter", "MultimediaProcessor"),
    "AIModelIntegration": ("dream.oneiric_engine.demo.dream_interpreter", "AIModelIntegration"),
    "QuickAccessRecorder": ("dream.oneiric_engine.demo.dream_interpreter", "QuickAccessRecorder"),
    "DreamEnhancer": ("dream.oneiric_engine.demo.dream_interpreter", "DreamEnhancer"),
    "MultimediaInputProcessor": ("dream.oneiric_engine.demo.dream_interpreter", "MultimediaInputProcessor"),
    "WebDreamInterpreter": ("dream.oneiric_engine.demo.web_app", "WebDreamInterpreter"),
    "UserRecord": ("dream.oneiric_engine.oneiric_core.db.user_repository", "UserRecord"),
    "DreamRequest": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "DreamRequest"),
    "DreamResponse": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "DreamResponse"),
    "EnhancedDreamEngine": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "EnhancedDreamEngine"),
    "SnapshotRequest": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "SnapshotRequest"),
    "SnapshotResponse": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "SnapshotResponse"),
    "QuantumDreamAdapter": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "QuantumDreamAdapter"),
    "DreamQuantumConfig": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "DreamQuantumConfig"),
    "BioOrchestrator": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "BioOrchestrator"),
    "QuantumBioOscillator": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "QuantumBioOscillator"),
    "UnifiedIntegration": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "UnifiedIntegration"),
    "DreamEngineSystem": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "DreamEngineSystem"),
    "DreamMemoryManager": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "DreamMemoryManager"),
    "DreamReflectionLoop": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "DreamReflectionLoop"),
    "DreamRequest": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_unified", "DreamRequest"),
    "DreamResponse": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_unified", "DreamResponse"),
    "SnapshotRequest": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_unified", "SnapshotRequest"),
    "SnapshotResponse": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_unified", "SnapshotResponse"),
    "AuthUser": ("dream.oneiric_engine.oneiric_core.identity.auth_middleware", "AuthUser"),
    "AuthUser": ("dream.oneiric_engine.oneiric_core.identity.auth_middleware_unified", "AuthUser"),
    "Settings": ("dream.oneiric_engine.oneiric_core.settings", "Settings"),
    "Config": ("dream.oneiric_engine.oneiric_core.settings", "Config"),
    "DreamLogger": ("dream.oneiric_engine.oneiric_core.utils.symbolic_logger", "DreamLogger"),
    "OpenAIDreamIntegration": ("dream.openai_dream_integration", "OpenAIDreamIntegration"),
    "DreamProcessor": ("dream.processors.dream_processor", "DreamProcessor"),
    "DreamProcessorIntegration": ("dream.processors.dream_processor_integrator", "DreamProcessorIntegration"),
    "DreamQuantumConfig": ("dream.quantum_dream_adapter", "DreamQuantumConfig"),
    "QuantumDreamAdapter": ("dream.quantum_dream_adapter", "QuantumDreamAdapter"),
    "RedirectJustifier": ("dream.redirect_justifier", "RedirectJustifier"),
    "RedirectTraceReplayer": ("dream.redirect_trace_replayer", "RedirectTraceReplayer"),
    "RLDreamCycle": ("dream.rl.rl_dream_cycle", "RLDreamCycle"),
    "RedirectForecaster": ("dream.stability.redirect_forecaster", "RedirectForecaster"),
    "DreamOperation": ("dream.symbolic.vocabulary", "DreamOperation"),
    "DreamSession": ("dream.tools.dream_divergence_map", "DreamSession"),
    "DriftScore": ("dream.tools.dream_divergence_map", "DriftScore"),
    "DriftMatrix": ("dream.tools.dream_divergence_map", "DriftMatrix"),
    "DreamDivergenceMapper": ("dream.tools.dream_divergence_map", "DreamDivergenceMapper"),
    "AnomalyType": ("dream.tools.symbolic_anomaly_explorer", "AnomalyType"),
    "AnomalySeverity": ("dream.tools.symbolic_anomaly_explorer", "AnomalySeverity"),
    "SymbolicTag": ("dream.tools.symbolic_anomaly_explorer", "SymbolicTag"),
    "DreamSession": ("dream.tools.symbolic_anomaly_explorer", "DreamSession"),
    "SymbolicAnomaly": ("dream.tools.symbolic_anomaly_explorer", "SymbolicAnomaly"),
    "AnomalyReport": ("dream.tools.symbolic_anomaly_explorer", "AnomalyReport"),
    "SymbolicAnomalyExplorer": ("dream.tools.symbolic_anomaly_explorer", "SymbolicAnomalyExplorer"),
    "MotifInstance": ("dream.tools.symbolic_theme_clusterer", "MotifInstance"),
    "SymbolicTheme": ("dream.tools.symbolic_theme_clusterer", "SymbolicTheme"),
    "ThemeTransition": ("dream.tools.symbolic_theme_clusterer", "ThemeTransition"),
    "ThematicEvolution": ("dream.tools.symbolic_theme_clusterer", "ThematicEvolution"),
    "SymbolicThemeClusterer": ("dream.tools.symbolic_theme_clusterer", "SymbolicThemeClusterer"),
    "DreamTimelineVisualizer": ("dream.visualization.dream_timeline_visualizer", "DreamTimelineVisualizer"),
    "DreamMemoryscapeViewport": ("dream.visualization.memoryscape_viewport", "DreamMemoryscapeViewport"),
    "DreamConvergenceTester": ("dream_systems.dream_convergence_tester", "DreamConvergenceTester"),
    "DreamDeliveryManager": ("dream_systems.dream_delivery_manager", "DreamDeliveryManager"),
    "VoiceSynthesisAdapter": ("dream_systems.dream_delivery_manager", "VoiceSynthesisAdapter"),
    "VoiceSafetyFilter": ("dream_systems.dream_delivery_manager", "VoiceSafetyFilter"),
    "DreamEmotionBridge": ("dream_systems.dream_emotion_bridge", "DreamEmotionBridge"),
    "EnhancedDreamEngine": ("dream_systems.dream_engine", "EnhancedDreamEngine"),
    "QuantumDreamAdapter": ("dream_systems.dream_engine", "QuantumDreamAdapter"),
    "DreamQuantumConfig": ("dream_systems.dream_engine", "DreamQuantumConfig"),
    "BioOrchestrator": ("dream_systems.dream_engine", "BioOrchestrator"),
    "QuantumBioOscillator": ("dream_systems.dream_engine", "QuantumBioOscillator"),
    "UnifiedIntegration": ("dream_systems.dream_engine", "UnifiedIntegration"),
    "DreamFeedbackController": ("dream_systems.dream_feedback_controller", "DreamFeedbackController"),
    "DreamPhase": ("dream_systems.dream_glyph_bridge", "DreamPhase"),
    "ArchetypalGlyphMapping": ("dream_systems.dream_glyph_bridge", "ArchetypalGlyphMapping"),
    "DreamSeed": ("dream_systems.dream_glyph_bridge", "DreamSeed"),
    "DreamGlyph": ("dream_systems.dream_glyph_bridge", "DreamGlyph"),
    "DreamGlyphBridge": ("dream_systems.dream_glyph_bridge", "DreamGlyphBridge"),
    "DreamLimiterConfig": ("dream_systems.dream_limiter", "DreamLimiterConfig"),
    "DreamLimiter": ("dream_systems.dream_limiter", "DreamLimiter"),
    "DreamLog": ("dream_systems.dream_log", "DreamLog"),
    "DreamLoopGenerator": ("dream_systems.dream_loop_generator", "DreamLoopGenerator"),
    "DreamReflectionLoop": ("dream_systems.dream_reflection_loop_simple", "DreamReflectionLoop"),
    "DreamSeed": ("dream_systems.dream_seed_simple", "DreamSeed"),
    "DreamSnapshotStore": ("dream_systems.dream_snapshot", "DreamSnapshotStore"),
    "DreamStatistics": ("dream_systems.dream_stats", "DreamStatistics"),
    "LegalComplianceAssistant": ("dream_systems.ethics_guard", "LegalComplianceAssistant"),
    "DreamQuantumConfig": ("dream_systems.quantum_dream_adapter", "DreamQuantumConfig"),
    "QuantumDreamAdapter": ("dream_systems.quantum_dream_adapter", "QuantumDreamAdapter"),
    "SnapshotRedirectionController": ("dream_systems.snapshot_redirection_controller", "SnapshotRedirectionController"),
    "VoiceParameter": ("dream_systems.voice_parameter", "VoiceParameter"),
    "DreamTimelineVisualizer": ("dream_timeline_visualizer", "DreamTimelineVisualizer"),
    "VoiceProfilingEmotionEngine": ("emotion.voice_profiling_emotion_engine", "VoiceProfilingEmotionEngine"),
    "VoiceProfilingEmotionEngine": ("emotion.voice_profiling_emotion_engine", "VoiceProfilingEmotionEngine"),
    "EmotionalResonance": ("emotional_resonance", "EmotionalResonance"),
    "ContentType": ("engines.engine", "ContentType"),
    "CreationRequest": ("engines.engine", "CreationRequest"),
    "LucasCreateEngine": ("engines.engine", "LucasCreateEngine"),
    "HealixVisualizer": ("healix_visualizer", "HealixVisualizer"),
    "ShynessModule": ("personality_engine", "ShynessModule"),
    "EtiquetteModule": ("personality_engine", "EtiquetteModule"),
    "HelpfulnessModule": ("personality_engine", "HelpfulnessModule"),
    "EthicalComplianceSystem": ("personality_engine", "EthicalComplianceSystem"),
    "CulturalIntelligenceModule": ("personality_engine", "CulturalIntelligenceModule"),
    "HumanizedAGI": ("personality_engine", "HumanizedAGI"),
    "QuantumCreativeBridge": ("quantum_creative_integration", "QuantumCreativeBridge"),
    "MockEngine": ("quantum_creative_integration", "MockEngine"),
    "CreativeExpression": ("quantum_creative_types", "CreativeExpression"),
    "QuantumContext": ("quantum_creative_types", "QuantumContext"),
    "QuantumHaiku": ("quantum_creative_types", "QuantumHaiku"),
    "QuantumMusicalPiece": ("quantum_creative_types", "QuantumMusicalPiece"),
    "SemanticField": ("quantum_creative_types", "SemanticField"),
    "QuantumWordState": ("quantum_creative_types", "QuantumWordState"),
    "CognitiveState": ("quantum_creative_types", "CognitiveState"),
    "EnhancedCreativeState": ("quantum_creative_types", "EnhancedCreativeState"),
    "CreatorIdentity": ("quantum_creative_types", "CreatorIdentity"),
    "ProtectedCreativeWork": ("quantum_creative_types", "ProtectedCreativeWork"),
    "CreativeParticipant": ("quantum_creative_types", "CreativeParticipant"),
    "CreativeGoal": ("quantum_creative_types", "CreativeGoal"),
    "SessionConfig": ("quantum_creative_types", "SessionConfig"),
    "CollaborativeCreation": ("quantum_creative_types", "CollaborativeCreation"),
    "UserCreativeProfile": ("quantum_creative_types", "UserCreativeProfile"),
    "CreativeInteraction": ("quantum_creative_types", "CreativeInteraction"),
    "PersonalizedCreation": ("quantum_creative_types", "PersonalizedCreation"),
    "CreativeRequest": ("quantum_creative_types", "CreativeRequest"),
    "UserSession": ("quantum_creative_types", "UserSession"),
    "CollaborativeSessionRequest": ("quantum_creative_types", "CollaborativeSessionRequest"),
    "QuantumCreativeComponent": ("quantum_creative_types", "QuantumCreativeComponent"),
    "QuantumImaginationProcessor": ("quantum_creative_types", "QuantumImaginationProcessor"),
    "QuantumEmotionEncoder": ("quantum_creative_types", "QuantumEmotionEncoder"),
    "CulturalQuantumMemory": ("quantum_creative_types", "CulturalQuantumMemory"),
    "NeuralCreativityNetwork": ("quantum_creative_types", "NeuralCreativityNetwork"),
    "SynapticInspirationPool": ("quantum_creative_types", "SynapticInspirationPool"),
    "DopamineRewardSystem": ("quantum_creative_types", "DopamineRewardSystem"),
    "ZeroKnowledgeCreativityValidator": ("quantum_creative_types", "ZeroKnowledgeCreativityValidator"),
    "QuantumVisualArtist": ("quantum_creative_types", "QuantumVisualArtist"),
    "QuantumStoryWeaver": ("quantum_creative_types", "QuantumStoryWeaver"),
    "QuantumCodePoet": ("quantum_creative_types", "QuantumCodePoet"),
    "QuantumChoreographer": ("quantum_creative_types", "QuantumChoreographer"),
    "Quantum3DSculptor": ("quantum_creative_types", "Quantum3DSculptor"),
    "SwarmCreativityOrchestrator": ("quantum_creative_types", "SwarmCreativityOrchestrator"),
    "CrossCulturalSynthesizer": ("quantum_creative_types", "CrossCulturalSynthesizer"),
    "QuantumSyllableCounter": ("quantum_creative_types", "QuantumSyllableCounter"),
    "SemanticEntangler": ("quantum_creative_types", "SemanticEntangler"),
    "EmotionImageryQuantumMapper": ("quantum_creative_types", "EmotionImageryQuantumMapper"),
    "PhoneticHarmonyAnalyzer": ("quantum_creative_types", "PhoneticHarmonyAnalyzer"),
    "KirejiQuantumSelector": ("quantum_creative_types", "KirejiQuantumSelector"),
    "SeasonalReferenceEncoder": ("quantum_creative_types", "SeasonalReferenceEncoder"),
    "HarmonicQuantumInspiredProcessor": ("quantum_creative_types", "HarmonicQuantumInspiredProcessor"),
    "RhythmPatternSuperposer": ("quantum_creative_types", "RhythmPatternSuperposer"),
    "EmotionalMelodyWeaver": ("quantum_creative_types", "EmotionalMelodyWeaver"),
    "CulturalScaleQuantumLibrary": ("quantum_creative_types", "CulturalScaleQuantumLibrary"),
    "NeuralOscillator": ("quantum_creative_types", "NeuralOscillator"),
    "DopamineCreativityModulator": ("quantum_creative_types", "DopamineCreativityModulator"),
    "SerotoninMoodHarmonizer": ("quantum_creative_types", "SerotoninMoodHarmonizer"),
    "NorepinephrineFocusEnhancer": ("quantum_creative_types", "NorepinephrineFocusEnhancer"),
    "AcetylcholineLearningBridge": ("quantum_creative_types", "AcetylcholineLearningBridge"),
    "SynapticPlasticityEngine": ("quantum_creative_types", "SynapticPlasticityEngine"),
    "REMDreamSynthesizer": ("quantum_creative_types", "REMDreamSynthesizer"),
    "CreativeBlockchain": ("quantum_creative_types", "CreativeBlockchain"),
    "QuantumWatermarkEmbedder": ("quantum_creative_types", "QuantumWatermarkEmbedder"),
    "CreativityMeshNetwork": ("quantum_creative_types", "CreativityMeshNetwork"),
    "QuantumIdeaSynthesizer": ("quantum_creative_types", "QuantumIdeaSynthesizer"),
    "CreativeConflictHarmonizer": ("quantum_creative_types", "CreativeConflictHarmonizer"),
    "EmergenceDetector": ("quantum_creative_types", "EmergenceDetector"),
    "QuantumAestheticProfiler": ("quantum_creative_types", "QuantumAestheticProfiler"),
    "CulturalResonanceTuner": ("quantum_creative_types", "CulturalResonanceTuner"),
    "EmotionalPreferenceLearner": ("quantum_creative_types", "EmotionalPreferenceLearner"),
    "CreativityStyleEvolver": ("quantum_creative_types", "CreativityStyleEvolver"),
    "CreativityMonitor": ("quantum_creative_types", "CreativityMonitor"),
    "CreativeEvolutionEngine": ("quantum_creative_types", "CreativeEvolutionEngine"),
    "NeuroHaikuGenerator": ("quantum_creative_types", "NeuroHaikuGenerator"),
    "CreativityService": ("service", "CreativityService"),
    "IdentityClient": ("service", "IdentityClient"),
    "CreativityService": ("services", "CreativityService"),
    "CreativeExpressionsCreativityEngine": ("systems.creative_expressions_creativity_engine", "CreativeExpressionsCreativityEngine"),
    "CreativeExpressionsEngine": ("systems.creative_expressions_creativity_engine", "CreativeExpressionsEngine"),
    "VocabularyCreativityEngine": ("systems.vocabulary_creativity_engine", "VocabularyCreativityEngine"),
    "VocabularyCreativityEngine": ("systems.vocabulary_creativity_engine", "VocabularyCreativityEngine"),
    "VoicePersonalityCreativityEngine": ("systems.voice_personality_creativity_engine", "VoicePersonalityCreativityEngine"),
    "EnhancedVoiceConfig": ("voice_integrator", "EnhancedVoiceConfig"),
    "EnhancedVoiceIntegrator": ("voice_integrator", "EnhancedVoiceIntegrator"),
}

# Function registry
_FUNCTION_REGISTRY = {
    "generate_neural_haiku": ("advanced_haiku_generator", "generate_neural_haiku"),
    "check_for_stagnation": ("affect_stagnation_detector", "check_for_stagnation"),
    "count_syllables": ("creative_engine", "count_syllables"),
    "generate_haiku": ("creative_expression_core", "generate_haiku"),
    "load_inspiration_profile": ("creative_expression_core", "load_inspiration_profile"),
    "update_reputation": ("creative_market", "update_reputation"),
    "export_item": ("creative_market", "export_item"),
    "collapse_to_expression": ("creative_q_expression", "collapse_to_expression"),
    "generate_haiku": ("creative_q_expression", "generate_haiku"),
    "react": ("dream.base.dream_refold.dream_refold", "react"),
    "get_coordinator_status": ("dream.colony_dream_coordinator", "get_coordinator_status"),
    "set_memory_module": ("dream.core", "set_memory_module"),
    "set_governance_module": ("dream.core", "set_governance_module"),
    "set_emotion_module": ("dream.core", "set_emotion_module"),
    "add_dream_metrics": ("dream.dashboard.dream_metrics_db", "add_dream_metrics"),
    "main": ("dream.dashboard.dream_metrics_view", "main"),
    "update_dream_metrics": ("dream.dashboard.dream_metrics_view", "update_dream_metrics"),
    "update_memory_metrics": ("dream.dashboard.dream_metrics_view", "update_memory_metrics"),
    "to_dict": ("dream.dashboard.dream_metrics_view", "to_dict"),
    "to_json": ("dream.dashboard.dream_metrics_view", "to_json"),
    "generate_dream": ("dream.dream_engine.oracle_dream", "generate_dream"),
    "replay_dream": ("dream.dream_engine.oracle_dream", "replay_dream"),
    "generate_flashback": ("dream.dream_engine.oracle_dream", "generate_flashback"),
    "log_dream": ("dream.dream_engine.oracle_dream", "log_dream"),
    "load_dream_log": ("dream.dream_engine.oracle_dream", "load_dream_log"),
    "generate_oracle_dream": ("dream.dream_engine.oracle_dream", "generate_oracle_dream"),
    "generate_dream": ("dream.dream_generator", "generate_dream"),
    "generate_dream_sync": ("dream.dream_generator", "generate_dream_sync"),
    "log_dream": ("dream.dream_log", "log_dream"),
    "load_latest_dream": ("dream.dream_mutator", "load_latest_dream"),
    "mutate_emotional_wave": ("dream.dream_mutator", "mutate_emotional_wave"),
    "mutate_dream": ("dream.dream_mutator", "mutate_dream"),
    "save_mutated_dream": ("dream.dream_mutator", "save_mutated_dream"),
    "dummy_evaluate": ("dream.dream_pipeline", "dummy_evaluate"),
    "allows": ("dream.dream_pipeline", "allows"),
    "pick_emotional_memory": ("dream.dream_pipeline", "pick_emotional_memory"),
    "mock_generate_ai_dream": ("dream.dream_sandbox", "mock_generate_ai_dream"),
    "to_dict": ("dream.dream_sandbox", "to_dict"),
    "set_dream_text": ("dream.dream_sandbox", "set_dream_text"),
    "interpret_dream_with_ai": ("dream.dream_sandbox", "interpret_dream_with_ai"),
    "mutate": ("dream.dream_sandbox", "mutate"),
    "step": ("dream.dream_sandbox", "step"),
    "run_recursive": ("dream.dream_sandbox", "run_recursive"),
    "generate_episodic_dream": ("dream.dream_seed", "generate_episodic_dream"),
    "generate_semantic_dream": ("dream.dream_seed", "generate_semantic_dream"),
    "seed_dream": ("dream.dream_seed", "seed_dream"),
    "load_dreams": ("dream.dream_stats", "load_dreams"),
    "summarize_dreams": ("dream.dream_stats", "summarize_dreams"),
    "get_engine_status": ("dream.engine.advanced_dream_engine", "get_engine_status"),
    "register_component": ("dream.engine.advanced_dream_engine", "register_component"),
    "run_adversarial_simulation": ("dream.engine.dream_engine", "run_adversarial_simulation"),
    "main": ("dream.engine.dream_engine_optimizer", "main"),
    "optimize_dream_processing_speed": ("dream.engine.dream_engine_optimizer", "optimize_dream_processing_speed"),
    "enhance_dream_quantum_coupling": ("dream.engine.dream_engine_optimizer", "enhance_dream_quantum_coupling"),
    "optimize_dream_memory_integration": ("dream.engine.dream_engine_optimizer", "optimize_dream_memory_integration"),
    "enhance_symbolic_dream_processing": ("dream.engine.dream_engine_optimizer", "enhance_symbolic_dream_processing"),
    "create_dream_performance_dashboard": ("dream.engine.dream_engine_optimizer", "create_dream_performance_dashboard"),
    "run_comprehensive_dream_enhancement": ("dream.engine.dream_engine_optimizer", "run_comprehensive_dream_enhancement"),
    "propagate": ("dream.feedback_propagator", "propagate"),
    "store_snapshot": ("dream.feedback_propagator", "store_snapshot"),
    "distance_to": ("dream.hyperspace_dream_simulator", "distance_to"),
    "interpolate": ("dream.hyperspace_dream_simulator", "interpolate"),
    "add_decision": ("dream.hyperspace_dream_simulator", "add_decision"),
    "add_outcome": ("dream.hyperspace_dream_simulator", "add_outcome"),
    "check_constraints": ("dream.hyperspace_dream_simulator", "check_constraints"),
    "add_timeline": ("dream.hyperspace_dream_simulator", "add_timeline"),
    "branch_timeline": ("dream.hyperspace_dream_simulator", "branch_timeline"),
    "find_optimal_timeline": ("dream.hyperspace_dream_simulator", "find_optimal_timeline"),
    "get_scenario_status": ("dream.hyperspace_dream_simulator", "get_scenario_status"),
    "get_system_status": ("dream.hyperspace_dream_simulator", "get_system_status"),
    "get_token_usage_report": ("dream.hyperspace_dream_simulator", "get_token_usage_report"),
    "get_dmb": ("dream.hyperspace_dream_simulator", "get_dmb"),
    "get_srd": ("dream.hyperspace_dream_simulator", "get_srd"),
    "instrument_reasoning": ("dream.hyperspace_dream_simulator", "instrument_reasoning"),
    "run_dream_breath": ("dream.immersive_ingestion", "run_dream_breath"),
    "mock_ai_complete": ("dream.oneiric_engine.demo.dream_interpreter", "mock_ai_complete"),
    "main": ("dream.oneiric_engine.demo.dream_interpreter", "main"),
    "test_dream_features": ("dream.oneiric_engine.demo.dream_interpreter", "test_dream_features"),
    "mock_generate_ai_dream": ("dream.oneiric_engine.demo.dream_interpreter", "mock_generate_ai_dream"),
    "to_dict": ("dream.oneiric_engine.demo.dream_interpreter", "to_dict"),
    "t": ("dream.oneiric_engine.demo.dream_interpreter", "t"),
    "set_dream_text": ("dream.oneiric_engine.demo.dream_interpreter", "set_dream_text"),
    "get_dream_prompt": ("dream.oneiric_engine.demo.dream_interpreter", "get_dream_prompt"),
    "parse_interpretation_response": ("dream.oneiric_engine.demo.dream_interpreter", "parse_interpretation_response"),
    "interpret_dream_with_ai": ("dream.oneiric_engine.demo.dream_interpreter", "interpret_dream_with_ai"),
    "enrich_dream_text": ("dream.oneiric_engine.demo.dream_interpreter", "enrich_dream_text"),
    "save_dream_entry": ("dream.oneiric_engine.demo.dream_interpreter", "save_dream_entry"),
    "get_dream_history": ("dream.oneiric_engine.demo.dream_interpreter", "get_dream_history"),
    "display_interpretation": ("dream.oneiric_engine.demo.dream_interpreter", "display_interpretation"),
    "interactive_session": ("dream.oneiric_engine.demo.dream_interpreter", "interactive_session"),
    "process_voice_input": ("dream.oneiric_engine.demo.dream_interpreter", "process_voice_input"),
    "analyze_image": ("dream.oneiric_engine.demo.dream_interpreter", "analyze_image"),
    "extract_url_content": ("dream.oneiric_engine.demo.dream_interpreter", "extract_url_content"),
    "add_emojis_to_text": ("dream.oneiric_engine.demo.dream_interpreter", "add_emojis_to_text"),
    "setup_client": ("dream.oneiric_engine.demo.dream_interpreter", "setup_client"),
    "start_quick_recording": ("dream.oneiric_engine.demo.dream_interpreter", "start_quick_recording"),
    "stop_recording": ("dream.oneiric_engine.demo.dream_interpreter", "stop_recording"),
    "quick_dream_capture": ("dream.oneiric_engine.demo.dream_interpreter", "quick_dream_capture"),
    "smart_emoji_enhancement": ("dream.oneiric_engine.demo.dream_interpreter", "smart_emoji_enhancement"),
    "add_symbolic_elements": ("dream.oneiric_engine.demo.dream_interpreter", "add_symbolic_elements"),
    "process_multiple_inputs": ("dream.oneiric_engine.demo.dream_interpreter", "process_multiple_inputs"),
    "ai_complete_function": ("dream.oneiric_engine.demo.web_app", "ai_complete_function"),
    "index": ("dream.oneiric_engine.demo.web_app", "index"),
    "interpret_dream": ("dream.oneiric_engine.demo.web_app", "interpret_dream"),
    "get_translations": ("dream.oneiric_engine.demo.web_app", "get_translations"),
    "to_json": ("dream.oneiric_engine.demo.web_app", "to_json"),
    "get_translations_for_locale": ("dream.oneiric_engine.demo.web_app", "get_translations_for_locale"),
    "init_db": ("dream.oneiric_engine.oneiric_core.db.db", "init_db"),
    "get_dream_engine": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "get_dream_engine"),
    "reflection_loop": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_fastapi", "reflection_loop"),
    "get_dream_engine": ("dream.oneiric_engine.oneiric_core.engine.dream_engine_unified", "get_dream_engine"),
    "lukhas_tier_required": ("dream.oneiric_engine.oneiric_core.identity.auth_middleware", "lukhas_tier_required"),
    "decorator": ("dream.oneiric_engine.oneiric_core.identity.auth_middleware", "decorator"),
    "oneiric_tier_required": ("dream.oneiric_engine.oneiric_core.identity.auth_middleware_unified", "oneiric_tier_required"),
    "require_lambda_tier": ("dream.oneiric_engine.oneiric_core.identity.auth_middleware_unified", "require_lambda_tier"),
    "decorator": ("dream.oneiric_engine.oneiric_core.identity.auth_middleware_unified", "decorator"),
    "run_migrations_offline": ("dream.oneiric_engine.oneiric_core.migrations.env", "run_migrations_offline"),
    "run_migrations_online": ("dream.oneiric_engine.oneiric_core.migrations.env", "run_migrations_online"),
    "upgrade": ("dream.oneiric_engine.oneiric_core.migrations.versions.20250710_add_users_table", "upgrade"),
    "downgrade": ("dream.oneiric_engine.oneiric_core.migrations.versions.20250710_add_users_table", "downgrade"),
    "upgrade": ("dream.oneiric_engine.oneiric_core.migrations.versions.20250726_add_unified_tier_support", "upgrade"),
    "downgrade": ("dream.oneiric_engine.oneiric_core.migrations.versions.20250726_add_unified_tier_support", "downgrade"),
    "get_settings": ("dream.oneiric_engine.oneiric_core.settings", "get_settings"),
    "validate_database_url": ("dream.oneiric_engine.oneiric_core.settings", "validate_database_url"),
    "validate_secret_strength": ("dream.oneiric_engine.oneiric_core.settings", "validate_secret_strength"),
    "log_dream": ("dream.oneiric_engine.oneiric_core.utils.symbolic_logger", "log_dream"),
    "get_logs": ("dream.oneiric_engine.oneiric_core.utils.symbolic_logger", "get_logs"),
    "db_url": ("dream.oneiric_engine.tests.conftest", "db_url"),
    "apply_migrations": ("dream.oneiric_engine.tests.conftest", "apply_migrations"),
    "reset_pool": ("dream.oneiric_engine.tests.conftest", "reset_pool"),
    "override_dependency": ("dream.oneiric_engine.tests.conftest", "override_dependency"),
    "justify": ("dream.redirect_justifier", "justify"),
    "replay_episode": ("dream.redirect_trace_replayer", "replay_episode"),
    "run_cycle": ("dream.rl.rl_dream_cycle", "run_cycle"),
    "forecast": ("dream.stability.redirect_forecaster", "forecast"),
    "get_dream_symbol": ("dream.symbolic.vocabulary", "get_dream_symbol"),
    "get_dream_narrative": ("dream.symbolic.vocabulary", "get_dream_narrative"),
    "get_visual_hint": ("dream.symbolic.vocabulary", "get_visual_hint"),
    "cycle_start": ("dream.symbolic.vocabulary", "cycle_start"),
    "phase_transition": ("dream.symbolic.vocabulary", "phase_transition"),
    "pattern_discovered": ("dream.symbolic.vocabulary", "pattern_discovered"),
    "insight_generated": ("dream.symbolic.vocabulary", "insight_generated"),
    "emotional_context": ("dream.symbolic.vocabulary", "emotional_context"),
    "memory_processing": ("dream.symbolic.vocabulary", "memory_processing"),
    "cycle_completion": ("dream.symbolic.vocabulary", "cycle_completion"),
    "trace_tag_flow": ("dream.tag_debug", "trace_tag_flow"),
    "main": ("dream.tools.dream_divergence_map", "main"),
    "calculate_entropy": ("dream.tools.dream_divergence_map", "calculate_entropy"),
    "calculate_emotional_magnitude": ("dream.tools.dream_divergence_map", "calculate_emotional_magnitude"),
    "extract_phase_markers": ("dream.tools.dream_divergence_map", "extract_phase_markers"),
    "to_dict": ("dream.tools.dream_divergence_map", "to_dict"),
    "get_max_drift_pair": ("dream.tools.dream_divergence_map", "get_max_drift_pair"),
    "get_high_drift_pairs": ("dream.tools.dream_divergence_map", "get_high_drift_pairs"),
    "load_dream_sessions": ("dream.tools.dream_divergence_map", "load_dream_sessions"),
    "compute_drift_matrix": ("dream.tools.dream_divergence_map", "compute_drift_matrix"),
    "extract_recurring_symbols": ("dream.tools.dream_divergence_map", "extract_recurring_symbols"),
    "render_divergence_map": ("dream.tools.dream_divergence_map", "render_divergence_map"),
    "generate_summary_json": ("dream.tools.dream_divergence_map", "generate_summary_json"),
    "main": ("dream.tools.run_dream_analysis", "main"),
    "analyze_recent_dreams": ("dream.tools.symbolic_anomaly_explorer", "analyze_recent_dreams"),
    "cli_analysis": ("dream.tools.symbolic_anomaly_explorer", "cli_analysis"),
    "extract_lambda_tags": ("dream.tools.symbolic_anomaly_explorer", "extract_lambda_tags"),
    "calculate_symbolic_density": ("dream.tools.symbolic_anomaly_explorer", "calculate_symbolic_density"),
    "to_dict": ("dream.tools.symbolic_anomaly_explorer", "to_dict"),
    "load_recent_dreams": ("dream.tools.symbolic_anomaly_explorer", "load_recent_dreams"),
    "detect_symbolic_anomalies": ("dream.tools.symbolic_anomaly_explorer", "detect_symbolic_anomalies"),
    "generate_anomaly_report": ("dream.tools.symbolic_anomaly_explorer", "generate_anomaly_report"),
    "summarize_symbolic_trends": ("dream.tools.symbolic_anomaly_explorer", "summarize_symbolic_trends"),
    "export_report_json": ("dream.tools.symbolic_anomaly_explorer", "export_report_json"),
    "export_summary_markdown": ("dream.tools.symbolic_anomaly_explorer", "export_summary_markdown"),
    "display_ascii_heatmap": ("dream.tools.symbolic_anomaly_explorer", "display_ascii_heatmap"),
    "main": ("dream.tools.symbolic_theme_clusterer", "main"),
    "extract_motifs_from_dreams": ("dream.tools.symbolic_theme_clusterer", "extract_motifs_from_dreams"),
    "cluster_motifs_by_similarity": ("dream.tools.symbolic_theme_clusterer", "cluster_motifs_by_similarity"),
    "summarize_theme_clusters": ("dream.tools.symbolic_theme_clusterer", "summarize_theme_clusters"),
    "track_theme_transitions": ("dream.tools.symbolic_theme_clusterer", "track_theme_transitions"),
    "render_theme_overview": ("dream.tools.symbolic_theme_clusterer", "render_theme_overview"),
    "avg_emotions": ("dream.tools.symbolic_theme_clusterer", "avg_emotions"),
    "render_timeline": ("dream.visualization.dream_timeline_visualizer", "render_timeline"),
    "load_dreams": ("dream.visualization.dream_viewer", "load_dreams"),
    "display_dreams": ("dream.visualization.dream_viewer", "display_dreams"),
    "render_scene": ("dream.visualization.memoryscape_viewport", "render_scene"),
    "load_latest_flashback": ("dream.visualization.visualizer_core", "load_latest_flashback"),
    "build_visual_prompt": ("dream.visualization.visualizer_core", "build_visual_prompt"),
    "run_convergence_test": ("dream_systems.dream_convergence_tester", "run_convergence_test"),
    "resume_symbolic_drift_probe": ("dream_systems.dream_convergence_tester", "resume_symbolic_drift_probe"),
    "modulate_voice_output": ("dream_systems.dream_delivery_manager", "modulate_voice_output"),
    "deliver_dream": ("dream_systems.dream_delivery_manager", "deliver_dream"),
    "synthesize": ("dream_systems.dream_delivery_manager", "synthesize"),
    "filter_content": ("dream_systems.dream_delivery_manager", "filter_content"),
    "trigger_dream_replay_if_needed": ("dream_systems.dream_emotion_bridge", "trigger_dream_replay_if_needed"),
    "adapt": ("dream_systems.dream_engine", "adapt"),
    "check_drift_event": ("dream_systems.dream_feedback_controller", "check_drift_event"),
    "trigger_redirection": ("dream_systems.dream_feedback_controller", "trigger_redirection"),
    "create_glyph_dream_seed": ("dream_systems.dream_glyph_bridge", "create_glyph_dream_seed"),
    "to_dict": ("dream_systems.dream_glyph_bridge", "to_dict"),
    "to_dict": ("dream_systems.dream_glyph_bridge", "to_dict"),
    "glyph_to_dream_seed": ("dream_systems.dream_glyph_bridge", "glyph_to_dream_seed"),
    "dream_to_glyph": ("dream_systems.dream_glyph_bridge", "dream_to_glyph"),
    "create_memory_consolidation_glyph": ("dream_systems.dream_glyph_bridge", "create_memory_consolidation_glyph"),
    "get_archetypal_dream_seeds": ("dream_systems.dream_glyph_bridge", "get_archetypal_dream_seeds"),
    "get_dream_glyph_lineage": ("dream_systems.dream_glyph_bridge", "get_dream_glyph_lineage"),
    "get_statistics": ("dream_systems.dream_glyph_bridge", "get_statistics"),
    "process_payload": ("dream_systems.dream_injector", "process_payload"),
    "run_batch_validation": ("dream_systems.dream_injector", "run_batch_validation"),
    "record_dream_message": ("dream_systems.dream_injector", "record_dream_message"),
    "filter_dreams": ("dream_systems.dream_limiter", "filter_dreams"),
    "log_dream": ("dream_systems.dream_log", "log_dream"),
    "get_recent_dreams": ("dream_systems.dream_log", "get_recent_dreams"),
    "generate_loop": ("dream_systems.dream_loop_generator", "generate_loop"),
    "reflect": ("dream_systems.dream_reflection_loop_simple", "reflect"),
    "is_stable": ("dream_systems.dream_reflection_loop_simple", "is_stable"),
    "replay_recent_dreams": ("dream_systems.dream_replay", "replay_recent_dreams"),
    "generate_episodic_dream": ("dream_systems.dream_seed", "generate_episodic_dream"),
    "generate_semantic_dream": ("dream_systems.dream_seed", "generate_semantic_dream"),
    "seed_dream": ("dream_systems.dream_seed", "seed_dream"),
    "generate_symbol": ("dream_systems.dream_seed_simple", "generate_symbol"),
    "save_snapshot": ("dream_systems.dream_snapshot", "save_snapshot"),
    "get_recent_snapshots": ("dream_systems.dream_snapshot", "get_recent_snapshots"),
    "update_stats": ("dream_systems.dream_stats", "update_stats"),
    "get_summary": ("dream_systems.dream_stats", "get_summary"),
    "get_trends": ("dream_systems.dream_stats", "get_trends"),
    "analyze_dream_symbols": ("dream_systems.dream_utils", "analyze_dream_symbols"),
    "merge_dream_sequences": ("dream_systems.dream_utils", "merge_dream_sequences"),
    "calculate_rem_phase": ("dream_systems.dream_utils", "calculate_rem_phase"),
    "dream_to_text": ("dream_systems.dream_utils", "dream_to_text"),
    "load_dreams": ("dream_systems.dream_viewer", "load_dreams"),
    "display_dreams": ("dream_systems.dream_viewer", "display_dreams"),
    "create_dream_superposition": ("dream_systems.quantum_dream_adapter", "create_dream_superposition"),
    "entangle_dreams": ("dream_systems.quantum_dream_adapter", "entangle_dreams"),
    "measure_quantum_like_state": ("dream_systems.quantum_dream_adapter", "measure_quantum_like_state"),
    "evolve_quantum_like_state": ("dream_systems.quantum_dream_adapter", "evolve_quantum_like_state"),
    "get_quantum_metrics": ("dream_systems.quantum_dream_adapter", "get_quantum_metrics"),
    "reset_quantum_like_state": ("dream_systems.quantum_dream_adapter", "reset_quantum_like_state"),
    "check_and_redirect": ("dream_systems.snapshot_redirection_controller", "check_and_redirect"),
    "calculate_redirect_severity": ("dream_systems.snapshot_redirection_controller", "calculate_redirect_severity"),
    "preemptive_stabilize": ("dream_systems.snapshot_redirection_controller", "preemptive_stabilize"),
    "render_timeline": ("dream_timeline_visualizer", "render_timeline"),
    "get_parameters_for_emotion": ("emotion.voice_profiling_emotion_engine", "get_parameters_for_emotion"),
    "get_provider_parameters": ("emotion.voice_profiling_emotion_engine", "get_provider_parameters"),
    "add_feedback": ("emotion.voice_profiling_emotion_engine", "add_feedback"),
    "record_usage": ("emotion.voice_profiling_emotion_engine", "record_usage"),
    "evolve": ("emotion.voice_profiling_emotion_engine", "evolve"),
    "to_dict": ("emotion.voice_profiling_emotion_engine", "to_dict"),
    "from_dict": ("emotion.voice_profiling_emotion_engine", "from_dict"),
    "create_profile": ("emotion.voice_profiling_emotion_engine", "create_profile"),
    "get_profile": ("emotion.voice_profiling_emotion_engine", "get_profile"),
    "list_profiles": ("emotion.voice_profiling_emotion_engine", "list_profiles"),
    "select_profile_for_context": ("emotion.voice_profiling_emotion_engine", "select_profile_for_context"),
    "record_usage": ("emotion.voice_profiling_emotion_engine", "record_usage"),
    "provide_feedback": ("emotion.voice_profiling_emotion_engine", "provide_feedback"),
    "delete_profile": ("emotion.voice_profiling_emotion_engine", "delete_profile"),
    "map_emotion": ("emotional_resonance", "map_emotion"),
    "analyze_emotional_trend": ("emotional_resonance", "analyze_emotional_trend"),
    "visualize_emotional_state": ("emotional_resonance", "visualize_emotional_state"),
    "generate_valence_arousal_plot": ("emotional_resonance", "generate_valence_arousal_plot"),
    "modulate_voice_parameters": ("emotional_resonance", "modulate_voice_parameters"),
    "get_emotion_from_context": ("emotional_resonance", "get_emotion_from_context"),
    "emotional_feedback_loop": ("emotional_resonance", "emotional_feedback_loop"),
    "get_capabilities": ("engines.engine", "get_capabilities"),
    "animate_frame": ("healix_visualizer", "animate_frame"),
    "handle_complex_scenario": ("personality_engine", "handle_complex_scenario"),
    "get_interaction_style": ("personality_engine", "get_interaction_style"),
    "adapt_behavior": ("personality_engine", "adapt_behavior"),
    "should_offer_help": ("personality_engine", "should_offer_help"),
    "resolve_dilemma": ("personality_engine", "resolve_dilemma"),
    "adjust_greeting": ("personality_engine", "adjust_greeting"),
    "interact": ("personality_engine", "interact"),
    "get_quantum_status": ("quantum_creative_integration", "get_quantum_status"),
    "get_system_status": ("quantum_creative_integration", "get_system_status"),
    "generate_haiku": ("quantum_creative_types", "generate_haiku"),
    "generate_content": ("service", "generate_content"),
    "synthesize_dream": ("service", "synthesize_dream"),
    "generate_emotional_content": ("service", "generate_emotional_content"),
    "generate_content": ("service", "generate_content"),
    "synthesize_dream": ("service", "synthesize_dream"),
    "generate_emotional_content": ("service", "generate_emotional_content"),
    "collaborate_creatively": ("service", "collaborate_creatively"),
    "verify_user_access": ("service", "verify_user_access"),
    "check_consent": ("service", "check_consent"),
    "log_activity": ("service", "log_activity"),
    "create_creativity_service": ("services", "create_creativity_service"),
    "generate_haiku": ("systems.creative_expressions_creativity_engine", "generate_haiku"),
    "load_inspiration_profile": ("systems.creative_expressions_creativity_engine", "load_inspiration_profile"),
    "generate_expression": ("systems.creative_expressions_creativity_engine", "generate_expression"),
    "generate_expression": ("systems.creative_expressions_creativity_engine", "generate_expression"),
    "get_symbol_for_analysis_type": ("systems.vocabulary_creativity_engine", "get_symbol_for_analysis_type"),
    "get_symbol_for_provider": ("systems.vocabulary_creativity_engine", "get_symbol_for_provider"),
    "get_dominant_color_symbol": ("systems.vocabulary_creativity_engine", "get_dominant_color_symbol"),
    "create_analysis_phrase": ("systems.vocabulary_creativity_engine", "create_analysis_phrase"),
    "get_emotional_color_mapping": ("systems.vocabulary_creativity_engine", "get_emotional_color_mapping"),
    "analyze_symbolic_composition": ("systems.vocabulary_creativity_engine", "analyze_symbolic_composition"),
    "get_quality_indicators": ("systems.vocabulary_creativity_engine", "get_quality_indicators"),
    "get_all_symbols": ("systems.vocabulary_creativity_engine", "get_all_symbols"),
    "get_context_symbols": ("systems.vocabulary_creativity_engine", "get_context_symbols"),
    "calculate_visual_harmony": ("systems.vocabulary_creativity_engine", "calculate_visual_harmony"),
    "get_voice_modulation": ("systems.voice_personality_creativity_engine", "get_voice_modulation"),
    "adapt_to_interaction": ("systems.voice_personality_creativity_engine", "adapt_to_interaction"),
}


def __getattr__(name):
    """Lazy import entities on access"""
    # Check class registry first
    if name in _ENTITY_REGISTRY:
        module_path, attr_name = _ENTITY_REGISTRY[name]
        try:
            module = importlib.import_module(f".{module_path}", package=__package__)
            return getattr(module, attr_name)
        except (ImportError, AttributeError) as e:
            logger.warning(f"Failed to import {attr_name} from {module_path}: {e}")
            raise AttributeError(f"module '{__name__}' has no attribute '{name}'")

    # Check function registry
    if name in _FUNCTION_REGISTRY:
        module_path, attr_name = _FUNCTION_REGISTRY[name]
        try:
            module = importlib.import_module(f".{module_path}", package=__package__)
            return getattr(module, attr_name)
        except (ImportError, AttributeError) as e:
            logger.warning(f"Failed to import {attr_name} from {module_path}: {e}")
            raise AttributeError(f"module '{__name__}' has no attribute '{name}'")

    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")


def __dir__():
    """List all available entities"""
    return list(_ENTITY_REGISTRY.keys()) + list(_FUNCTION_REGISTRY.keys())


# Export commonly used entities directly for better IDE support
__all__ = [
    "AdvancedHaikuGenerator",
    "QuantumHaikuGenerator",
    "NeuroHaikuGenerator",
    "AffectStagnationDetector",
    "CreativeStyle",
    "ExpansionStrategy",
    "CreativeConfig",
    "CreativeMetrics",
    "CreativeContext",
    "NeuralCreativeModel",
    "SymbolicKnowledgeBase",
    "FederatedLearningClient",
    "CircuitBreaker",
    "AdvancedSyllableAnalyzer",
    "EnterpriseNeuralHaikuGenerator",
    "CreativeEngineFactory",
    "MockNeuralModel",
    "MockSymbolicKB",
    "MockFederatedClient",
    "NeuroHaikuGenerator",
]

# System metadata
__system__ = "creativity"
__total_entities__ = 572
__classes__ = 274
__functions__ = 298
