from __future__ import annotations
# ██╗      ██████╗  ██████╗ ██╗  ██╗ █████╗ ███████╗
# ██║     ██╔═══██╗██╔════╝ ██║  ██║██╔══██╗██╔════╝
# ██║     ██║   ██║██║  ███╗███████║███████║███████╗
# ██║     ██║   ██║██║   ██║██╔══██║██╔══██║╚════██║
# ███████╗╚██████╔╝╚██████╔╝██║  ██║██║  ██║███████║
# ╚══════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝
# LUKHAS™ (2024) - LUKHAS High-Performance AI System
#
# Desc: Type alias for reasoning effort levels, potentially auto-generated.
# Docs: https://github.com/LUKHAS-AI/lukhas-docs/blob/main/reasoning_effort_type.md
# Λssociated: Used by various reasoning modules to specify effort.
#
# THIS FILE IS ΛUTOGENERATED AND MANAGED BY LUKHAS AI.
# (Potentially auto-generated by Stainless from OpenAPI spec - see original header)
# MANUAL MODIFICATIONS MAY BE OVERWRITTEN IF RE-GENERATED.
#
# Copyright (C) 2024 LUKHAS AI. All rights reserved.
# Use of this source code is governed by a LUKHAS AI license
# that can be found in the LICENSE file.
#
# Contact: contact@lukhas.ai
# Website: https://lukhas.ai
#
"""
# ΛNOTE: This module defines the symbolic type `ReasoningEffort`, standardizing how
# different levels of computational or cognitive effort for reasoning tasks are specified
# across the LUKHAS system. Its auto-generated nature (from OpenAPI by Stainless)
# suggests it plays a role in API contracts or system-wide type consistency.

Defines a type alias for specifying the level of reasoning effort.

This file appears to be auto-generated by Stainless from an OpenAPI specification.
It provides a standardized way to represent reasoning effort levels (low, medium, high)
throughout the LUKHAS system.
"""

# Original Stainless generation comment:
# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.


from typing import Optional
from typing_extensions import Literal, TypeAlias

import structlog

# Initialize ΛTRACE logger for this module
logger = structlog.get_logger("ΛTRACE.reasoning.reasoning_effort")
logger.info("ΛTRACE: Initializing reasoning_effort.py module (TypeAlias definition).", module_path=__file__)

__all__ = ["ReasoningEffort"]

# Human-readable comment: Defines the allowed values for ReasoningEffort.
# ΛNOTE: The ReasoningEffort TypeAlias symbolically quantifies the allocated
# resources or depth for a reasoning task into discrete levels (low, medium, high).
# This allows components to request or specify the intensity of reasoning required.
ReasoningEffort: TypeAlias = Optional[Literal["low", "medium", "high"]]
logger.debug("ReasoningEffort TypeAlias defined.", definition='Optional[Literal["low", "medium", "high"]]') # Removed manual ΛTRACE

# ═══════════════════════════════════════════════════════════════════════════
# LUKHAS AI - Reasoning Effort Type Definition
#
# Module: reasoning.reasoning_effort
# Version: 1.1.0 (Standardization Pass)
# Function: Defines the `ReasoningEffort` type alias, likely used to indicate
#           the computational or cognitive intensity for reasoning operations.
# Origin: Auto-generated by Stainless from an OpenAPI specification (as per original header).
#
# Integration: This type alias is intended for use in function/method signatures
#              across various LUKHAS reasoning modules where specifying an effort
#              level is required.
# ═══════════════════════════════════════════════════════════════════════════
# Standard LUKHAS File Footer - Do Not Modify
# File ID: reasoning_effort_type_v1.1.0_20240712
# Revision: 1_initial_standardization_001
# Checksum (SHA256): placeholder_checksum_generated_at_commit_time
# Last Review: 2024-Jul-12 by Jules System Agent
# ═══════════════════════════════════════════════════════════════════════════
# END OF FILE: reasoning/reasoning_effort.py
# ═══════════════════════════════════════════════════════════════════════════
