# ██╗      ██████╗  ██████╗ ██╗  ██╗ █████╗ ███████╗
# ██║     ██╔═══██╗██╔════╝ ██║  ██║██╔══██╗██╔════╝
# ██║     ██║   ██║██║  ███╗███████║███████║███████╗
# ██║     ██║   ██║██║   ██║██╔══██║██╔══██║╚════██║
# ███████╗╚██████╔╝╚██████╔╝██║  ██║██║  ██║███████║
# ╚══════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝
# LUKHAS™ (2024) - LUKHAS High-Performance AI System
#
# Desc: Data model for response reasoning summary delta events, likely auto-generated.
# Docs: https://github.com/LUKHAS-AI/lukhas-docs/blob/main/reasoning_events.md
# Λssociated: Other response_reasoning_*.py event models.
#
# THIS FILE IS ΛUTOGENERATED AND MANAGED BY LUKHAS AI.
# (Likely auto-generated by Stainless from OpenAPI spec - see original header)
# MANUAL MODIFICATIONS MAY BE OVERWRITTEN IF RE-GENERATED.
#
# Copyright (C) 2024 LUKHAS AI. All rights reserved.
# Use of this source code is governed by a LUKHAS AI license
# that can be found in the LICENSE file.
#
# Contact: contact@lukhas.ai
# Website: https://lukhas.ai
#
"""
# ΛNOTE: This module defines the `ResponseReasoningSummaryDeltaEvent` data model.
# This symbolic structure is used for conveying incremental updates to a reasoning summary,
# facilitating streaming or progressive display of summarized reasoning information.
# Its auto-generated nature from an OpenAPI spec implies it's part of a defined API contract.

Defines the data model for a 'response reasoning summary delta' event.

This file appears to be auto-generated by Stainless from an OpenAPI specification.
It specifies the structure for events that represent partial updates to a reasoning
summary, likely used in streaming responses.
"""

# Original Stainless generation comment:
# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal

# AIMPORT_TODO: Verify the location of `_models.BaseModel`.
# ΛAUTO_GEN_PATH: This relative import `from core.models import BaseModel` is likely from auto-generation.
# See reasoning/README_reasoning_trace.md -> Auto-Gen Import Note
# If `_models.BaseModel` is part of a core LUKHAS framework library, an absolute import
# (e.g., `from core_framework.core.models import BaseModel`) would be more robust.
# ΛCAUTION: Fragile import path can lead to runtime errors and maintenance issues.
from core.models import BaseModel # Assuming this path is correct within the project structure.

import structlog

# Initialize ΛTRACE logger for this module
logger = structlog.get_logger("ΛTRACE.reasoning.response_reasoning_summary_delta_event")
logger.info("ΛTRACE: Initializing response_reasoning_summary_delta_event.py module (Data Model Definition).", module_path=__file__)

__all__ = ["ResponseReasoningSummaryDeltaEvent"]


# ΛNOTE: This class defines the symbolic structure for a delta event specifically for a reasoning summary.
# It allows for incremental updates to a summary associated with a larger reasoning item.
class ResponseReasoningSummaryDeltaEvent(BaseModel):
    """
    Represents a partial update (delta) to a reasoning summary content part.
    This is used for streaming updates to reasoning summaries.
    """
    # ΛNOTE: The `delta` field carries the incremental update to the summary content.
    delta: object # Kept as 'object'; could be Union[str, Dict] if the summary content structure is known
    """The partial update to the reasoning summary content."""

    # AIDENTITY: `item_id` links this summary delta to the parent reasoning item.
    item_id: str
    """
    The unique identifier of the main reasoning item to which this summary belongs.
    """

    output_index: int
    """The index of the overall output item (e.g., a message) in the response's output array."""

    # ΛNOTE: `sequence_number` ensures ordered application of summary deltas.
    sequence_number: int
    """The sequence number of this delta event for the specific summary part, ensuring ordered application."""

    # ΛNOTE: `summary_index` identifies which part of a potentially multi-part summary is being updated.
    summary_index: int
    """The index of this specific summary part within the reasoning item's summary list."""

    # ΛNOTE: `type` is a fixed literal, symbolically identifying this event's specific purpose.
    type: Literal["response.reasoning_summary.delta"]
    """The type of the event. Always 'response.reasoning_summary.delta' for this model."""
    # Human-readable comment: Fixed literal type for event discrimination.

logger.debug("ResponseReasoningSummaryDeltaEvent data model class defined.", class_name="ResponseReasoningSummaryDeltaEvent") # Removed manual ΛTRACE prefix

# ═══════════════════════════════════════════════════════════════════════════
# LUKHAS AI - Response Reasoning Summary Delta Event Model
#
# Module: reasoning.response_reasoning_summary_delta_event
# Version: 1.1.0 (Standardization Pass)
# Function: Defines the data structure for events representing partial updates
#           to a reasoning summary.
# Origin: Auto-generated by Stainless from an OpenAPI specification (as per original header).
#
# Integration: Used in systems that stream reasoning summaries, allowing for
#              progressive display or processing. Depends on `BaseModel` from the
#              LUKHAS framework.
# ═══════════════════════════════════════════════════════════════════════════
# Standard LUKHAS File Footer - Do Not Modify
# File ID: reasoning_resp_sum_delta_evt_v1.1.0_20240712
# Revision: 1_initial_standardization_001
# Checksum (SHA256): placeholder_checksum_generated_at_commit_time
# Last Review: 2024-Jul-12 by Jules System Agent
# ═══════════════════════════════════════════════════════════════════════════
# END OF FILE: reasoning/response_reasoning_summary_delta_event.py
# ═══════════════════════════════════════════════════════════════════════════
