# ██╗      ██████╗  ██████╗ ██╗  ██╗ █████╗ ███████╗
# ██║     ██╔═══██╗██╔════╝ ██║  ██║██╔══██╗██╔════╝
# ██║     ██║   ██║██║  ███╗███████║███████║███████╗
# ██║     ██║   ██║██║   ██║██╔══██║██╔══██║╚════██║
# ███████╗╚██████╔╝╚██████╔╝██║  ██║██║  ██║███████║
# ╚══════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝
# LUKHAS™ (2024) - LUKHAS High-Performance AI System
#
# Desc: Data model for 'reasoning summary text delta' events, likely auto-generated.
# Docs: https://github.com/LUKHAS-AI/lukhas-docs/blob/main/reasoning_events.md
# Λssociated: Other response_reasoning_*.py event models.
#
# THIS FILE IS ΛUTOGENERATED AND MANAGED BY LUKHAS AI.
# (Likely auto-generated by Stainless from OpenAPI spec - see original header)
# MANUAL MODIFICATIONS MAY BE OVERWRITTEN IF RE-GENERATED.
#
# Copyright (C) 2024 LUKHAS AI. All rights reserved.
# Use of this source code is governed by a LUKHAS AI license
# that can be found in the LICENSE file.
#
# Contact: contact@lukhas.ai
# Website: https://lukhas.ai
#
"""
# ΛNOTE: This module defines the `ResponseReasoningSummaryTextDeltaEvent` data model.
# This symbolic structure is designed to convey incremental textual updates (deltas)
# to a part of a reasoning summary. This is essential for streaming applications where
# reasoning text is built or displayed progressively. Auto-generated from OpenAPI.

Defines the data model for a 'response reasoning summary text delta' event.

This file appears to be auto-generated by Stainless from an OpenAPI specification.
It specifies the structure for events representing a textual delta (partial update)
to a reasoning summary, typically used in streaming responses.
"""

# Original Stainless generation comment:
# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal

# AIMPORT_TODO: Verify the location of `_models.BaseModel`.
# ΛAUTO_GEN_PATH: This relative import `from core.models import BaseModel` is likely from auto-generation.
# See reasoning/README_reasoning_trace.md -> Auto-Gen Import Note
# If `_models.BaseModel` is part of a core LUKHAS framework library, an absolute import
# (e.g., `from core_framework.core.models import BaseModel`) would be more robust.
# ΛCAUTION: Fragile import path can lead to runtime errors and maintenance issues.
from core.models import BaseModel # Assuming this path is correct within the project structure.

import structlog

# Initialize ΛTRACE logger for this module
logger = structlog.get_logger("ΛTRACE.reasoning.response_reasoning_summary_text_delta_event")
logger.info("ΛTRACE: Initializing response_reasoning_summary_text_delta_event.py module (Data Model Definition).", module_path=__file__)

__all__ = ["ResponseReasoningSummaryTextDeltaEvent"]


# ΛNOTE: This class defines the symbolic structure for an event carrying a textual
# delta for a reasoning summary part. It's crucial for streaming applications
# where text is generated and sent incrementally.
class ResponseReasoningSummaryTextDeltaEvent(BaseModel):
    """
    Represents an event carrying a textual delta (partial update) for a reasoning summary part.
    This is used for streaming text content of reasoning summaries.
    """
    # ΛNOTE: `delta` contains the actual incremental piece of symbolic text for the summary.
    delta: str
    """The text delta (a piece of text) that was added to the summary part."""

    # AIDENTITY: `item_id` links this text delta to the parent reasoning item's summary.
    item_id: str
    """The unique identifier of the main reasoning item to which this summary text delta applies."""

    output_index: int
    """The index of the overall output item (e.g., a message) in the response's output array."""

    # ΛNOTE: `sequence_number` ensures that textual deltas are applied in the correct order
    # to reconstruct the summary accurately.
    sequence_number: int
    """The sequence number of this event, crucial for correctly ordering text deltas."""

    # ΛNOTE: `summary_index` identifies which specific part of a multi-part summary this text delta pertains to.
    summary_index: int
    """The index of the specific summary part (within the reasoning item's summary list)
       that this text delta belongs to."""

    # ΛNOTE: `type` is a fixed literal, symbolically identifying this event's specific purpose for text deltas of summaries.
    type: Literal["response.reasoning_summary_text.delta"]
    """The type of the event. Always 'response.reasoning_summary_text.delta' for this model."""
    # Human-readable comment: Fixed literal type for event discrimination.

logger.debug("ResponseReasoningSummaryTextDeltaEvent data model class defined.", class_name="ResponseReasoningSummaryTextDeltaEvent") # Removed manual ΛTRACE prefix

# ═══════════════════════════════════════════════════════════════════════════
# LUKHAS AI - Response Reasoning Summary Text Delta Event Model
#
# Module: reasoning.response_reasoning_summary_text_delta_event
# Version: 1.1.0 (Standardization Pass)
# Function: Defines the data structure for events representing textual deltas
#           (partial updates) to a reasoning summary part.
# Origin: Auto-generated by Stainless from an OpenAPI specification (as per original header).
#
# Integration: Used in systems that stream textual components of reasoning summaries,
#              allowing for progressive rendering or processing of text. Depends on
#              `BaseModel` from the LUKHAS framework.
# ═══════════════════════════════════════════════════════════════════════════
# Standard LUKHAS File Footer - Do Not Modify
# File ID: reasoning_resp_sum_txt_delta_evt_v1.1.0_20240712
# Revision: 1_initial_standardization_001
# Checksum (SHA256): placeholder_checksum_generated_at_commit_time
# Last Review: 2024-Jul-12 by Jules System Agent
# ═══════════════════════════════════════════════════════════════════════════
# END OF FILE: reasoning/response_reasoning_summary_text_delta_event.py
# ═══════════════════════════════════════════════════════════════════════════
