# ██╗      ██████╗  ██████╗ ██╗  ██╗ █████╗ ███████╗
# ██║     ██╔═══██╗██╔════╝ ██║  ██║██╔══██╗██╔════╝
# ██║     ██║   ██║██║  ███╗███████║███████║███████╗
# ██║     ██║   ██║██║   ██║██╔══██║██╔══██║╚════██║
# ███████╗╚██████╔╝╚██████╔╝██║  ██║██║  ██║███████║
# ╚══════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝
# LUKHAS™ (2024) - LUKHAS High-Performance AI System
#
# Desc: Data model for response reasoning done events, likely auto-generated.
# Docs: https://github.com/LUKHAS-AI/lukhas-docs/blob/main/reasoning_events.md
# Λssociated: Other response_reasoning_*.py event models.
#
# THIS FILE IS ΛUTOGENERATED AND MANAGED BY LUKHAS AI.
# (Likely auto-generated by Stainless from OpenAPI spec - see original header)
# MANUAL MODIFICATIONS MAY BE OVERWRITTEN IF RE-GENERATED.
#
# Copyright (C) 2024 LUKHAS AI. All rights reserved.
# Use of this source code is governed by a LUKHAS AI license
# that can be found in the LICENSE file.
#
# Contact: contact@lukhas.ai
# Website: https://lukhas.ai
#
"""
# ΛNOTE: This module defines the symbolic data structure `ResponseReasoningDoneEvent`.
# This event signifies the completion of a specific reasoning item or thought process
# within a larger response generation sequence. It's likely used in event-driven systems
# to signal that a particular piece of reasoning is finalized and its full content is available.
# Its auto-generated nature (from OpenAPI by Stainless) points to its role in a formal system interface.

Defines the data model for a 'response reasoning done' event.

This file appears to be auto-generated by Stainless from an OpenAPI specification
and defines the structure for events indicating the finalization of a specific
reasoning content part within a response.
"""

# Original Stainless generation comment:
# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal
# AIMPORT_TODO: Verify the location of `_models.BaseModel`.
# ΛAUTO_GEN_PATH: This relative import `from core.models import BaseModel` is likely from auto-generation.
# See reasoning/README_reasoning_trace.md -> Auto-Gen Import Note
# If `_models.BaseModel` is part of a core LUKHAS framework library, an absolute import
# (e.g., `from core_framework.core.models import BaseModel`) would be more robust.
# ΛCAUTION: Fragile import path can lead to runtime errors and maintenance issues.
from core.models import BaseModel # Assuming this path is correct within the project structure.

import structlog

# Initialize ΛTRACE logger for this module
logger = structlog.get_logger("ΛTRACE.reasoning.response_reasoning_done_event")
logger.info("ΛTRACE: Initializing response_reasoning_done_event.py module (Data Model Definition).", module_path=__file__)

__all__ = ["ResponseReasoningDoneEvent"]


# ΛNOTE: This class defines the symbolic structure for an event indicating that a
# specific part of the reasoning process for a response is complete. It carries
# the finalized content and identifiers for correlation.
class ResponseReasoningDoneEvent(BaseModel):
    """
    Represents an event indicating that a specific reasoning content part
    within a response item has been finalized.
    """
    content_index: int
    """The index of the reasoning content part within the output item that has been finalized."""

    # AIDENTITY: `item_id` uniquely identifies the specific reasoning component (e.g., a thought node, a sub-query)
    # that has concluded its process.
    item_id: str
    """The unique identifier of the reasoning item (e.g., a thought or step) that is now complete."""

    output_index: int
    """The index of the overall output item (e.g., a message or response block) in the response's
       output array to which this finalized reasoning item belongs."""

    # ΛNOTE: `sequence_number` marks the final sequence for this item, ensuring that this "done" event
    # is processed after all preceding delta events for the same item. It's key for symbolic ordering.
    sequence_number: int
    """The sequence number of this 'done' event, corresponding to the final sequence number
       of any delta events for this item."""

    # ΛNOTE: `text` contains the complete, finalized symbolic output of the reasoning item.
    text: str
    """The complete and finalized reasoning text for this item."""

    # ΛNOTE: The `type` field is a fixed literal, a symbolic discriminator for event type handling.
    type: Literal["response.reasoning.done"]
    """The type of the event. Always 'response.reasoning.done' for this model."""
    # Human-readable comment: This fixed literal type is used for event discrimination.

logger.debug("ResponseReasoningDoneEvent data model class defined.", class_name="ResponseReasoningDoneEvent") # Removed manual ΛTRACE prefix

# ═══════════════════════════════════════════════════════════════════════════
# LUKHAS AI - Response Reasoning Done Event Model
#
# Module: reasoning.response_reasoning_done_event
# Version: 1.1.0 (Standardization Pass)
# Function: Defines the data structure for events signaling the completion
#           of a reasoning content part in a response.
# Origin: Auto-generated by Stainless from an OpenAPI specification (as per original header).
#
# Integration: Used in systems where reasoning is streamed or progressively updated,
#              marking the end of updates for a particular reasoning item. Relies on
#              a `BaseModel` from the LUKHAS framework.
# ═══════════════════════════════════════════════════════════════════════════
# Standard LUKHAS File Footer - Do Not Modify
# File ID: reasoning_resp_done_evt_v1.1.0_20240712
# Revision: 1_initial_standardization_001
# Checksum (SHA256): placeholder_checksum_generated_at_commit_time
# Last Review: 2024-Jul-12 by Jules System Agent
# ═══════════════════════════════════════════════════════════════════════════
# END OF FILE: reasoning/response_reasoning_done_event.py
# ═══════════════════════════════════════════════════════════════════════════
