# ██╗      ██████╗  ██████╗ ██╗  ██╗ █████╗ ███████╗
# ██║     ██╔═══██╗██╔════╝ ██║  ██║██╔══██╗██╔════╝
# ██║     ██║   ██║██║  ███╗███████║███████║███████╗
# ██║     ██║   ██║██║   ██║██╔══██║██╔══██║╚════██║
# ███████╗╚██████╔╝╚██████╔╝██║  ██║██║  ██║███████║
# ╚══════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝
# LUKHAS™ (2024) - LUKHAS High-Performance AI System
#
# Desc: Data model for response reasoning summary done events, likely auto-generated.
# Docs: https://github.com/LUKHAS-AI/lukhas-docs/blob/main/reasoning_events.md
# Λssociated: Other response_reasoning_*.py event models.
#
# THIS FILE IS ΛUTOGENERATED AND MANAGED BY LUKHAS AI.
# (Likely auto-generated by Stainless from OpenAPI spec - see original header)
# MANUAL MODIFICATIONS MAY BE OVERWRITTEN IF RE-GENERATED.
#
# Copyright (C) 2024 LUKHAS AI. All rights reserved.
# Use of this source code is governed by a LUKHAS AI license
# that can be found in the LICENSE file.
#
# Contact: contact@lukhas.ai
# Website: https://lukhas.ai
#
"""
# ΛNOTE: This module defines the `ResponseReasoningSummaryDoneEvent` data model.
# This symbolic structure signals the completion of a specific reasoning summary part,
# providing its final content. Useful in event-driven systems for assembling complete
# reasoning summaries from potentially streamed parts. Auto-generated from OpenAPI.

Defines the data model for a 'response reasoning summary done' event.

This file appears to be auto-generated by Stainless from an OpenAPI specification.
It specifies the structure for events indicating the finalization of a specific
reasoning summary part within a response.
"""

# Original Stainless generation comment:
# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal

# AIMPORT_TODO: Verify the location of `_models.BaseModel`.
# ΛAUTO_GEN_PATH: This relative import `from core.models import BaseModel` is likely from auto-generation.
# See reasoning/README_reasoning_trace.md -> Auto-Gen Import Note
# If `_models.BaseModel` is part of a core LUKHAS framework library, an absolute import
# (e.g., `from core_framework.core.models import BaseModel`) would be more robust.
# ΛCAUTION: Fragile import path can lead to runtime errors and maintenance issues.
from core.models import BaseModel # Assuming this path is correct within the project structure.

import structlog

# Initialize ΛTRACE logger for this module
logger = structlog.get_logger("ΛTRACE.reasoning.response_reasoning_summary_done_event")
logger.info("ΛTRACE: Initializing response_reasoning_summary_done_event.py module (Data Model Definition).", module_path=__file__)

__all__ = ["ResponseReasoningSummaryDoneEvent"]


# ΛNOTE: This class defines the symbolic structure for an event signaling the completion
# of a specific reasoning summary part. It provides the final text and necessary identifiers.
class ResponseReasoningSummaryDoneEvent(BaseModel):
    """
    Represents an event indicating that a specific reasoning summary part
    within a response item has been finalized.
    """
    # AIDENTITY: `item_id` links this completed summary part back to its parent reasoning item.
    item_id: str
    """The unique identifier of the main reasoning item for which this summary part is finalized."""

    output_index: int
    """The index of the overall output item (e.g., a message) in the response's output array."""

    # ΛNOTE: `sequence_number` indicates the final sequence for this summary part,
    # crucial for ensuring correct assembly if parts were streamed.
    sequence_number: int
    """The final sequence number for this summary part, corresponding to the last delta event if streamed."""

    # ΛNOTE: `summary_index` identifies which specific part of a multi-part summary is now complete.
    summary_index: int
    """The index of this specific summary part within the reasoning item's summary list."""

    # ΛNOTE: `text` contains the complete and finalized symbolic content of the reasoning summary part.
    text: str
    """The complete and finalized reasoning summary text for this part."""

    # ΛNOTE: `type` is a fixed literal, symbolically identifying this event's specific purpose.
    type: Literal["response.reasoning_summary.done"]
    """The type of the event. Always 'response.reasoning_summary.done' for this model."""
    # Human-readable comment: Fixed literal type for event discrimination.

logger.debug("ResponseReasoningSummaryDoneEvent data model class defined.", class_name="ResponseReasoningSummaryDoneEvent") # Removed manual ΛTRACE prefix

# ═══════════════════════════════════════════════════════════════════════════
# LUKHAS AI - Response Reasoning Summary Done Event Model
#
# Module: reasoning.response_reasoning_summary_done_event
# Version: 1.1.0 (Standardization Pass)
# Function: Defines the data structure for events signaling the completion
#           of a reasoning summary part in a response.
# Origin: Auto-generated by Stainless from an OpenAPI specification (as per original header).
#
# Integration: Used in systems that stream reasoning summaries, marking the end
#              of updates for a particular summary part. Depends on `BaseModel`
#              from the LUKHAS framework.
# ═══════════════════════════════════════════════════════════════════════════
# Standard LUKHAS File Footer - Do Not Modify
# File ID: reasoning_resp_sum_done_evt_v1.1.0_20240712
# Revision: 1_initial_standardization_001
# Checksum (SHA256): placeholder_checksum_generated_at_commit_time
# Last Review: 2024-Jul-12 by Jules System Agent
# ═══════════════════════════════════════════════════════════════════════════
# END OF FILE: reasoning/response_reasoning_summary_done_event.py
# ═══════════════════════════════════════════════════════════════════════════
