# ██╗      ██████╗  ██████╗ ██╗  ██╗ █████╗ ███████╗
# ██║     ██╔═══██╗██╔════╝ ██║  ██║██╔══██╗██╔════╝
# ██║     ██║   ██║██║  ███╗███████║███████║███████╗
# ██║     ██║   ██║██║   ██║██╔══██║██╔══██║╚════██║
# ███████╗╚██████╔╝╚██████╔╝██║  ██║██║  ██║███████║
# ╚══════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝
# LUKHAS™ (2024) - LUKHAS High-Performance AI System
#
# Desc: Data model for 'reasoning summary text done' events, likely auto-generated.
# Docs: https://github.com/LUKHAS-AI/lukhas-docs/blob/main/reasoning_events.md
# Λssociated: Other response_reasoning_*.py event models.
#
# THIS FILE IS ΛUTOGENERATED AND MANAGED BY LUKHAS AI.
# (Likely auto-generated by Stainless from OpenAPI spec - see original header)
# MANUAL MODIFICATIONS MAY BE OVERWRITTEN IF RE-GENERATED.
#
# Copyright (C) 2024 LUKHAS AI. All rights reserved.
# Use of this source code is governed by a LUKHAS AI license
# that can be found in the LICENSE file.
#
# Contact: contact@lukhas.ai
# Website: https://lukhas.ai
#
"""
# ΛNOTE: This module defines the `ResponseReasoningSummaryTextDoneEvent` data model.
# This symbolic structure signals that the textual content for a specific reasoning summary part
# has been fully transmitted or finalized. It's used in streaming contexts to mark the
# completion of a text segment within a summary. Auto-generated from OpenAPI.

Defines the data model for a 'response reasoning summary text done' event.

This file appears to be auto-generated by Stainless from an OpenAPI specification.
It specifies the structure for events indicating the finalization of the text
content for a specific reasoning summary part.
"""

# Original Stainless generation comment:
# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal

# AIMPORT_TODO: Verify the location of `_models.BaseModel`.
# ΛAUTO_GEN_PATH: This relative import `from core.models import BaseModel` is likely from auto-generation.
# See reasoning/README_reasoning_trace.md -> Auto-Gen Import Note
# If `_models.BaseModel` is part of a core LUKHAS framework library, an absolute import
# (e.g., `from core_framework.core.models import BaseModel`) would be more robust.
# ΛCAUTION: Fragile import path can lead to runtime errors and maintenance issues.
from core.models import BaseModel # Assuming this path is correct within the project structure.

import structlog

# Initialize ΛTRACE logger for this module
logger = structlog.get_logger("ΛTRACE.reasoning.response_reasoning_summary_text_done_event")
logger.info("ΛTRACE: Initializing response_reasoning_summary_text_done_event.py module (Data Model Definition).", module_path=__file__)

__all__ = ["ResponseReasoningSummaryTextDoneEvent"]


# ΛNOTE: This class defines the symbolic structure for an event signaling that the text
# content for a specific reasoning summary part is complete.
class ResponseReasoningSummaryTextDoneEvent(BaseModel):
    """
    Represents an event indicating that the text content for a specific
    reasoning summary part has been finalized.
    """
    # AIDENTITY: `item_id` links this completed summary text back to its parent reasoning item.
    item_id: str
    """The unique identifier of the main reasoning item to which this summary text belongs."""

    output_index: int
    """The index of the overall output item (e.g., a message) in the response's output array."""

    # ΛNOTE: `sequence_number` marks the final sequence for this summary text part,
    # ensuring it's processed after all its constituent deltas.
    sequence_number: int
    """The final sequence number for this summary text, corresponding to the last text delta event."""

    # ΛNOTE: `summary_index` identifies which specific part of a multi-part summary this text completion refers to.
    summary_index: int
    """The index of the specific summary part (within the reasoning item's summary list)
       for which the text is now complete."""

    # ΛNOTE: `text` contains the complete and finalized symbolic text for this summary part.
    text: str
    """The full and finalized text of the completed reasoning summary part."""

    # ΛNOTE: `type` is a fixed literal, a symbolic discriminator for this specific event.
    type: Literal["response.reasoning_summary_text.done"]
    """The type of the event. Always 'response.reasoning_summary_text.done' for this model."""
    # Human-readable comment: Fixed literal type for event discrimination.

logger.debug("ResponseReasoningSummaryTextDoneEvent data model class defined.", class_name="ResponseReasoningSummaryTextDoneEvent") # Removed manual ΛTRACE prefix

# ═══════════════════════════════════════════════════════════════════════════
# LUKHAS AI - Response Reasoning Summary Text Done Event Model
#
# Module: reasoning.response_reasoning_summary_text_done_event
# Version: 1.1.0 (Standardization Pass)
# Function: Defines the data structure for events signaling the completion of
#           the text content for a reasoning summary part.
# Origin: Auto-generated by Stainless from an OpenAPI specification (as per original header).
#
# Integration: Used in systems that stream textual components of reasoning summaries,
#              marking the end of text updates for a particular summary part.
#              Depends on `BaseModel` from the LUKHAS framework.
# ═══════════════════════════════════════════════════════════════════════════
# Standard LUKHAS File Footer - Do Not Modify
# File ID: reasoning_resp_sum_txt_done_evt_v1.1.0_20240712
# Revision: 1_initial_standardization_001
# Checksum (SHA256): placeholder_checksum_generated_at_commit_time
# Last Review: 2024-Jul-12 by Jules System Agent
# ═══════════════════════════════════════════════════════════════════════════
# END OF FILE: reasoning/response_reasoning_summary_text_done_event.py
# ═══════════════════════════════════════════════════════════════════════════
