# ██╗      ██████╗  ██████╗ ██╗  ██╗ █████╗ ███████╗
# ██║     ██╔═══██╗██╔════╝ ██║  ██║██╔══██╗██╔════╝
# ██║     ██║   ██║██║  ███╗███████║███████║███████╗
# ██║     ██║   ██║██║   ██║██╔══██║██╔══██║╚════██║
# ███████╗╚██████╔╝╚██████╔╝██║  ██║██║  ██║███████║
# ╚══════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝
# LUKHAS™ (2024) - LUKHAS High-Performance AI System
#
# Desc: Data model for 'reasoning summary part added' events, likely auto-generated.
# Docs: https://github.com/LUKHAS-AI/lukhas-docs/blob/main/reasoning_events.md
# Λssociated: Other response_reasoning_*.py event models.
#
# THIS FILE IS ΛUTOGENERATED AND MANAGED BY LUKHAS AI.
# (Likely auto-generated by Stainless from OpenAPI spec - see original header)
# MANUAL MODIFICATIONS MAY BE OVERWRITTEN IF RE-GENERATED.
#
# Copyright (C) 2024 LUKHAS AI. All rights reserved.
# Use of this source code is governed by a LUKHAS AI license
# that can be found in the LICENSE file.
#
# Contact: contact@lukhas.ai
# Website: https://lukhas.ai
#
"""
# ΛNOTE: This module defines data models (`Part`, `ResponseReasoningSummaryPartAddedEvent`)
# for events that signal the addition of a new segment to a reasoning summary.
# These symbolic structures are likely used in streaming architectures to progressively
# build and communicate reasoning summaries. Auto-generated from OpenAPI.

Defines data models for a 'response reasoning summary part added' event.

This file appears to be auto-generated by Stainless from an OpenAPI specification.
It specifies structures for events indicating that a new part of a reasoning
summary has been added, typically used in streaming or progressive responses.
"""

# Original Stainless generation comment:
# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal

# AIMPORT_TODO: Verify the location of `_models.BaseModel`.
# ΛAUTO_GEN_PATH: This relative import `from core.models import BaseModel` is likely from auto-generation.
# See reasoning/README_reasoning_trace.md -> Auto-Gen Import Note
# If `_models.BaseModel` is part of a core LUKHAS framework library, an absolute import
# (e.g., `from core_framework.core.models import BaseModel`) would be more robust.
# ΛCAUTION: Fragile import path can lead to runtime errors and maintenance issues.
from core.models import BaseModel # Assuming this path is correct within the project structure.

import structlog

# Initialize ΛTRACE logger for this module
logger = structlog.get_logger("ΛTRACE.reasoning.response_reasoning_summary_part_added_event")
logger.info("ΛTRACE: Initializing response_reasoning_summary_part_added_event.py module (Data Model Definition).", module_path=__file__)

__all__ = ["ResponseReasoningSummaryPartAddedEvent", "Part"]


# ΛNOTE: The `Part` class defines the symbolic structure for a segment of a reasoning summary,
# usually containing text and a type discriminator.
class Part(BaseModel):
    """
    Represents a part of a reasoning summary, typically a text segment.
    """
    # ΛNOTE: The `text` field holds the symbolic content of this summary part.
    text: str
    """The text content of this summary part."""

    # ΛNOTE: `type` is a fixed literal, symbolically identifying this as a 'summary_text' part.
    type: Literal["summary_text"]
    """The type of this summary part. Always `summary_text` for this model."""
    # Human-readable comment: Fixed literal type for discriminating this model part.
logger.debug("Part data model class (for summary part) defined.", class_name="Part") # Removed manual ΛTRACE prefix


# ΛNOTE: This class, `ResponseReasoningSummaryPartAddedEvent`, defines the symbolic structure
# for an event indicating a new part has been added to a reasoning summary. It links the new
# part to its parent reasoning item and provides sequencing information.
class ResponseReasoningSummaryPartAddedEvent(BaseModel):
    """
    Represents an event indicating that a new part has been added to a reasoning summary.
    This is used for streaming or progressively building reasoning summaries.
    """
    # AIDENTITY: `item_id` links this new summary part to its parent reasoning item.
    item_id: str
    """The unique identifier of the main reasoning item to which this summary part belongs."""

    output_index: int
    """The index of the overall output item (e.g., a message) in the response's output array
       with which this summary part is associated."""

    # ΛNOTE: `part` contains the actual symbolic content of the summary segment being added.
    part: Part
    """The actual summary part content that was added."""

    # ΛNOTE: `sequence_number` is crucial for the correct ordered assembly of summary parts.
    sequence_number: int
    """The sequence number of this event, ensuring ordered processing if multiple parts are added."""

    # ΛNOTE: `summary_index` indicates the position of this new part within the overall summary list for the item.
    summary_index: int
    """The index of this newly added summary part within the reasoning item's list of summary parts."""

    # ΛNOTE: `type` is a fixed literal, symbolically identifying this event's specific purpose.
    type: Literal["response.reasoning_summary_part.added"]
    """The type of the event. Always 'response.reasoning_summary_part.added' for this model."""
    # Human-readable comment: Fixed literal type for event discrimination.

logger.debug("ResponseReasoningSummaryPartAddedEvent data model class defined.", class_name="ResponseReasoningSummaryPartAddedEvent") # Removed manual ΛTRACE prefix

# ═══════════════════════════════════════════════════════════════════════════
# LUKHAS AI - Response Reasoning Summary Part Added Event Model
#
# Module: reasoning.response_reasoning_summary_part_added_event
# Version: 1.1.0 (Standardization Pass)
# Function: Defines data structures for events signaling the addition of a new
#           part to a reasoning summary.
# Origin: Auto-generated by Stainless from an OpenAPI specification (as per original header).
#
# Integration: Used in systems that stream or progressively build reasoning summaries.
#              Depends on `BaseModel` from the LUKHAS framework.
# ═══════════════════════════════════════════════════════════════════════════
# Standard LUKHAS File Footer - Do Not Modify
# File ID: reasoning_resp_sum_part_add_evt_v1.1.0_20240712
# Revision: 1_initial_standardization_001
# Checksum (SHA256): placeholder_checksum_generated_at_commit_time
# Last Review: 2024-Jul-12 by Jules System Agent
# ═══════════════════════════════════════════════════════════════════════════
# END OF FILE: reasoning/response_reasoning_summary_part_added_event.py
# ═══════════════════════════════════════════════════════════════════════════
