# Configuration files for the Quantum-Secure AI System

# Quantum Computing Configuration
quantum:
  backend: "qasm_simulator"  # or "aer_simulator", "ibm_quantum"
  max_qubits: 20
  error_mitigation: true
  noise_model: "realistic"
  circuit_optimization_level: 3

# Security Configuration
security:
  post_quantum_crypto:
    primary_kem: "CRYSTALS-Kyber"
    primary_signature: "CRYSTALS-Dilithium"
    security_level: 5  # AES-256 equivalent
    hybrid_mode: true
    key_rotation_interval_hours: 24
  
  zero_knowledge:
    default_proof_system: "adaptive"
    circuit_cache_size: 1000
    trusted_setup_required: false
  
  homomorphic_encryption:
    scheme: "CKKS"
    precision_bits: 40
    security_parameter: 128

# Distributed Computing Configuration
distributed:
  ray_cluster:
    head_node_host: "127.0.0.1"
    head_node_port: 10001
    num_cpus: 8
    num_gpus: 1
  
  consensus:
    algorithm: "quantum_byzantine_ft"
    byzantine_tolerance: 0.33
    timeout_seconds: 30

# Memory Configuration
memory:
  quantum_memory:
    capacity_qubits: 10
    error_correction: "surface_code"
    decoherence_mitigation: "dynamical_decoupling"
  
  classical_cache:
    max_size_gb: 10
    eviction_policy: "lru"

# Audit and Compliance
audit:
  blockchain:
    block_size: 100
    mining_difficulty: 4
    consensus_algorithm: "proof_of_stake"
  
  compliance_frameworks:
    - "GDPR"
    - "CCPA"
    - "PIPEDA"
    - "LGPD"

# Telemetry and Monitoring
telemetry:
  encryption_level: "homomorphic"
  export_endpoint: "https://telemetry.quantum-secure.ai"
  metrics_retention_days: 30
