repos:
  - repo: local
    hooks:
      - id: check-cross-layer
        name: Check Cross-Layer Dependencies
        entry: python scripts/check_cross_layer.py
        language: system
        pass_filenames: false
        always_run: true
        
      - id: check-circular-imports
        name: Check Circular Imports
        entry: python scripts/check_circular_imports.py
        language: system
        pass_filenames: false
        always_run: true
        
      - id: no-lukhas-prefix
        name: Check for lukhas_ prefix
        entry: bash -c 'if find . -name "lukhas_*.py" | grep -v __pycache__ | grep -v .venv | head -1; then echo "Found files with lukhas_ prefix"; exit 1; fi'
        language: system
        pass_filenames: false
        
      - id: python-syntax-check
        name: Check Python Syntax
        entry: python -m py_compile
        language: system
        types: [python]
        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict